"""LLM report generation worker for pipeline."""
import asyncio
from datetime import datetime, date
from typing import List, Dict, Any, Optional
from uuid import UUID

from tradercat.logger.logger import get_logger
from tradercat.config import settings

logger = get_logger(__name__)


class ReportWorker:
    """Worker for generating LLM-based analysis reports."""
    
    def __init__(self, max_retries: int = 1):
        """
        Initialize report worker.
        
        Args:
            max_retries: Number of retries per report on LLM failure
        """
        self.max_retries = max_retries
    
    async def generate_report(
        self,
        user_id: UUID,
        symbol: str,
        run_date: date,
        signal_context: Dict[str, Any],
        pipeline_run_id: UUID,
        model: Optional[str] = None,
        persona: Optional[str] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Generate a report for a symbol using LLM.
        
        Args:
            user_id: User ID
            symbol: Stock symbol
            run_date: Date of the report
            signal_context: Context including today's and past signals
            pipeline_run_id: Pipeline run ID
            model: LLM model to use (defaults to settings)
            persona: Analyst persona to use (defaults to settings)
            
        Returns:
            Report record ready for database insertion, or None on failure
        """
        model = model or settings.default_llm_model
        persona = persona or settings.default_persona
        
        for attempt in range(self.max_retries + 1):
            try:
                # TODO: Integrate actual LLM provider
                # For now, generate a placeholder report
                report_content = await self._generate_llm_report(
                    symbol, signal_context, model, persona
                )
                
                return {
                    "user_id": user_id,
                    "run_date": run_date,
                    "symbol": symbol,
                    "report_type": "symbol_analysis",
                    "content_md": report_content,
                    "model_used": model,
                    "persona_used": persona,
                    "input_context": signal_context,
                    "pipeline_run_id": pipeline_run_id,
                }
                
            except Exception as e:
                if attempt < self.max_retries:
                    logger.warning(f"Retry {attempt + 1}/{self.max_retries} for {symbol} report: {e}")
                    await asyncio.sleep(2 ** attempt)  # Exponential backoff
                else:
                    logger.error(f"Failed to generate report for {symbol} after {self.max_retries + 1} attempts: {e}")
                    return None
        
        return None
    
    async def _generate_llm_report(
        self,
        symbol: str,
        signal_context: Dict[str, Any],
        model: str,
        persona: str
    ) -> str:
        """
        Generate report content using LLM.
        
        This is a placeholder - actual implementation would use:
        - tradercat.ai.stock_analyst.AIStockAnalyst
        - tradercat.ai.llm_provider_factory
        """
        # TODO: Integrate with existing AI infrastructure
        # from tradercat.ai.llm_provider_factory import get_llm_provider
        # from tradercat.ai.prompt_manager import PromptManager
        # from tradercat.ai.stock_analyst import AIStockAnalyst
        
        # Placeholder report
        today_signals = signal_context.get("today_signals", [])
        past_signals = signal_context.get("past_3d_signals", [])
        global_signals = signal_context.get("global_signals", [])
        
        report = f"""# {symbol} Analysis Report - {signal_context.get('run_date', 'N/A')}

## Trading Signals

### Today's Signals ({len(today_signals)})
"""
        for sig in today_signals:
            report += f"- **{sig.get('strategy')}**: {sig.get('signal').upper()} (confidence: {sig.get('confidence'):.2f})\n"
            report += f"  - {sig.get('reason', 'N/A')}\n"
        
        report += f"\n### Past 3 Days Summary ({len(past_signals)} signals)\n"
        report += "\n### Market Context\n"
        
        for sig in global_signals[:3]:  # Show top 3 global signals
            report += f"- {sig.get('symbol')}: {sig.get('signal').upper()} ({sig.get('strategy')})\n"
        
        report += "\n---\n*Generated by TraderCat API (model: " + model + ", persona: " + persona + ")*\n"
        
        return report


async def generate_reports_concurrent(
    report_tasks: List[Dict[str, Any]],
    max_concurrency: int = 5
) -> List[Dict[str, Any]]:
    """
    Generate multiple reports concurrently using a queue and workers.
    
    Args:
        report_tasks: List of report task specifications
        max_concurrency: Maximum number of concurrent workers
        
    Returns:
        List of all report records
    """
    queue = asyncio.Queue()
    results = []
    
    # Enqueue all tasks
    for task in report_tasks:
        await queue.put(task)
    
    # Worker coroutine
    async def worker():
        worker_results = []
        report_worker = ReportWorker()
        
        while True:
            try:
                task = queue.get_nowait()
            except asyncio.QueueEmpty:
                break
            
            try:
                report_record = await report_worker.generate_report(**task)
                if report_record:
                    worker_results.append(report_record)
            finally:
                queue.task_done()
        
        return worker_results
    
    # Spawn workers
    workers = [asyncio.create_task(worker()) for _ in range(min(max_concurrency, len(report_tasks)))]
    
    # Wait for all workers to complete
    worker_results = await asyncio.gather(*workers)
    
    # Flatten results
    for result_list in worker_results:
        results.extend(result_list)
    
    return results
