"""User report generation worker for pipeline (Q3).

Q3 generates personalized reports per user by:
1. Loading the macro summary from Q2 (global_reports).
2. Loading the symbol execution plans for the user's watchlist from Q2.
3. Calling LLM with the user's preferred persona to produce a personalized briefing.
"""
import asyncio
from datetime import date
from typing import List, Dict, Any, Optional
from uuid import UUID

from tradercat.logger.logger import get_logger
from tradercat.config import settings

logger = get_logger(__name__)


class UserReportWorker:
    """Worker for generating personalized user reports (Q3)."""
    
    def __init__(self, max_retries: int | None = None):
        self.max_retries = max_retries if max_retries is not None else settings.pipeline_llm_max_retries
    
    async def generate_user_briefing(
        self,
        user_id: UUID,
        run_date: date,
        summary_report_md: str,
        symbol_plans: Dict[str, str],  # symbol → execution plan markdown
        persona: str,
        lang: str | None,
        pipeline_run_id: UUID,
        model: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Generate a personalized briefing for a user.
        
        Combines the macro summary + relevant symbol execution plans,
        then calls LLM with the user's preferred persona for a personalized output.
        """
        model = model or settings.default_llm_model
        persona_key = persona
        if lang and lang != "en":
            persona_key = f"{persona}-{lang}"
        
        for attempt in range(self.max_retries + 1):
            try:
                content = await self._call_llm_personalized(
                    summary_report_md=summary_report_md,
                    symbol_plans=symbol_plans,
                    persona=persona_key,
                    model=model,
                )
                
                return {
                    "user_id": user_id,
                    "run_date": run_date,
                    "report_type": "personalized_briefing",
                    "content_md": content,
                    "model_used": model,
                    "persona_used": persona_key,
                    "input_context": {
                        "symbols": list(symbol_plans.keys()),
                        "persona": persona_key,
                        "has_summary": bool(summary_report_md),
                    },
                    "pipeline_run_id": pipeline_run_id,
                }
                
            except Exception as e:
                if attempt < self.max_retries:
                    logger.warning(f"Q3: Retry {attempt + 1}/{self.max_retries} for user {user_id}: {e}")
                    await asyncio.sleep(2 ** attempt)
                else:
                    logger.error(
                        f"Q3: Failed to generate briefing for user {user_id} "
                        f"after {self.max_retries + 1} attempts: {e}"
                    )
                    return None
        
        return None
    
    async def _call_llm_personalized(
        self,
        summary_report_md: str,
        symbol_plans: Dict[str, str],
        persona: str,
        model: str,
    ) -> str:
        """
        Call LLM with persona to generate personalized briefing.
        
        TODO: Integrate with tradercat.ai infrastructure.
        Uses PromptManager to load persona system prompt.
        """
        # Placeholder - will be replaced with actual LLM call
        symbols = list(symbol_plans.keys())
        
        report = f"""# Your Daily Trading Briefing

**Persona**: {persona} | **Model**: {model} | **Symbols**: {len(symbols)}

---

## Market Overview

{summary_report_md[:500] if summary_report_md else '*No macro summary available*'}

---

## Your Watchlist

"""
        for symbol, plan in symbol_plans.items():
            # Extract first few lines of each plan
            plan_preview = "\n".join(plan.split("\n")[:10])
            report += f"### {symbol}\n\n{plan_preview}\n\n"
        
        report += """---

## Personalized Recommendations

*Pending LLM integration with persona: """ + persona + """*

---
*Generated by TraderCat Pipeline Q3*
"""
        return report


async def generate_user_reports_q3(
    user_tasks: List[Dict[str, Any]],
    max_concurrency: int = 5,
) -> List[Dict[str, Any]]:
    """
    Q3: Generate personalized reports for all users concurrently.
    
    Each user_task should contain:
        - user_id: UUID
        - run_date: date
        - summary_report_md: str (from Q2)
        - symbol_plans: Dict[str, str] (from Q2, filtered to user's watchlist)
        - persona: str
        - lang: str | None
        - pipeline_run_id: UUID
    """
    if not user_tasks:
        return []
    
    queue = asyncio.Queue()
    for task in user_tasks:
        await queue.put(task)
    
    async def worker():
        results = []
        w = UserReportWorker()
        while True:
            try:
                task = queue.get_nowait()
            except asyncio.QueueEmpty:
                break
            try:
                record = await w.generate_user_briefing(**task)
                if record:
                    results.append(record)
            finally:
                queue.task_done()
        return results
    
    workers = [
        asyncio.create_task(worker())
        for _ in range(min(max_concurrency, len(user_tasks)))
    ]
    worker_results = await asyncio.gather(*workers)
    
    all_records = []
    for result_list in worker_results:
        all_records.extend(result_list)
    
    logger.info(f"Q3 complete: {len(all_records)} user reports from {len(user_tasks)} tasks")
    return all_records
