# # Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# # More GitHub Actions for Azure: https://github.com/Azure/actions
# # More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - TraderCat

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55A43A4145C84481B3D7A6319590225C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E58F9AE278F4489E8B6DCFFEC6887B8B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_992E3A0D4C0F43BAA39A7CAFCFBA1CEE }}

      - name: Deploy to Azure Functions (Remote Build)
        uses: Azure/functions-action@v1
        with:
          app-name: "TraderCat"
          slot-name: "Production"
          package: "." # Root of your function app
          remote-build: true
